import turtle
screen = turtle.Screen()
t=turtle.Turtle()
screen.bgcolor("black")
t.shape('turtle')
t.color("yellow")
for i in range(10):
    t.circle(30)
    t.forward(10)
t.goto(0,0)
for x in range(10): 
    t.right(90)
    t.forward(20)
    t.backward(20)
    t.left(90)
    t.forward(10)
t.goto(120,0)
t.circle(40)
t.left(90)
t.penup()
t.forward(15)
t.pendown()
t.dot()
t.penup()
t.right(90)
t.forward(15)
t.pendown()
t.dot()
t.penup()
t.forward(30)

